### ISSUE TITLE
support for records

### ISSUE THREAD

**Issue by carocad** [mortalapeman/birch-lt#4]
Well first of all some big thanks for making this :) it is a huge help while debugging.

I have a problem though: If I want to watch the content of a record then birch crashes. I guess your regex didn't take them into account, but the strings representation that lighttable outputs should be quite similar to normal maps right?

This is specially problematic if you have collections of records, where Lighttable outputs too much type information, thus blurring the information that the user might be interested in.

**Comment by carocad** [comment]
closing this due to lack of follow up

**Comment by mortalapeman** [comment]
Yeah, my bad. I life changed and was unable to continue committing time to the project. You're totally welcome to fork the repo and mess around with it @carocad .
